language: node_js
node_js:
- '5.7'
cache:
  directories:
  - node_modules
notifications:
  slack:
    secure: cLEC1dQoTRgP13HevnIfX18lk8F0zG6hHEVJVvg6UWPSFL9p+ZhRKnFPDwyiJlrH8zAbRrYzvWJn4axZIUYnEU39OkdrZZiDpC8XNGnnxZn9POEGnytChYGSYNXNXZp53Vz9wwELGWcr3hZrCXv47jYbCt2iicX8X44T/Qo1QIXINx8QzkhaPHVkG/GNdsZHHDil9sjYZf4WyWkdKdQxwbCZtKEKb2zhv7timT5RKoPz5wnAIE262IDHRtIJo5AZEQ8diBynB8xPoaZWME5wPmQl9A2r7lF1r6tubdonM3KklLbRUF4kiPqvGrzA0a8gwdWCpAukkpl223CvvSVoHUwL5I8NUsXIP9JQSfskMAMgb/mcm7YOs3I4CJJCA5HQOe2hCbcX61MFXtqbmP45m7tOeNLeC/2XwPQRqTfE023+T7sYhmopTbDbbn9GNBISYv02NhRqcJ44+1YAivCL/JvETW8xwpcEyq6Ok6peBBspLxArlbxJ4+5J2c7ioaOXGMx8CpRnIpDrPCNI2O0wp+cqivR3T70fxMxgNSwnKE81OjzfQ8nvslpM8+42SzvY91cQMQ5r7RQRteDE+VJj2MqZDpKh+WzggRLVgR3BPIrP3846bwyW/WR84Elh8UphiB4632NyJVP957hkd7FTklF/e2T1XndQ4nsuC1aFbGM=
